import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// import components
import Layout from '../components/Layout/Layout'
import Poster from '../components/Poster/Poster'
import AboutUs from '../components/aboutUs/AboutUs'
import LastContents from '../components/LastContents/LastContents'
import MostSell from '../components/MostSell/MostSell'


export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Poster />
          <AboutUs />
          <LastContents />
          <LastContents />
          {/* <MostSell /> */}
        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </Layout>
  )
}
